const countries = [
  { country: 'Австралия', continent: 'europe' },
  { country: 'Австрия', continent: 'asia' },
  { country: 'Азербайджан', continent: 'asia' },
  { country: 'Албания', continent: 'europe' },
  { country: 'Алжир', continent: 'africa' },
  { country: 'Ангола', continent: 'africa' },
  { country: 'Андорра', continent: 'europe' },
  { country: 'Антигуа и Барбуда', continent: 'islands' },
  { country: 'Аргентина', continent: 'america' },
  { country: 'Армения', continent: 'asia' },
  { country: 'Афганистан', continent: 'asia' },
  { country: 'Багамские Острова', continent: 'islands' },
  { country: 'Бангладеш', continent: 'asia' },
  { country: 'Барбадос', continent: 'islands' },
  { country: 'Бахрейн', continent: 'asia' },
  { country: 'Белоруссия', continent: 'europe' },
  { country: 'Белиз', continent: 'america' },
  { country: 'Бельгия', continent: 'europe' },
  { country: 'Бенин', continent: 'africa' },
  { country: 'Болгария', continent: 'europe' },
  { country: 'Боливия', continent: 'america' },
  { country: 'Босния и Герцеговина', continent: 'europe' },
  { country: 'Ботсвана', continent: 'africa' },
  { country: 'Бразилия', continent: 'america' },
  { country: 'Бруней', continent: 'asia' },
  { country: 'Буркина-Фасо', continent: 'africa' },
  { country: 'Бурунди', continent: 'africa' },
  { country: 'Бутан', continent: 'asia' },
  { country: 'Вануату', continent: 'islands' },
  { country: 'Великобритания', continent: 'europe' },
  { country: 'Венгрия', continent: 'europe' },
  { country: 'Венесуэла', continent: 'america' },
  { country: 'Восточный Тимор', continent: 'asia' },
  { country: 'Вьетнам', continent: 'asia' },
  { country: 'Габон', continent: 'africa' },
  { country: 'Гаити', continent: 'islands' },
  { country: 'Гайана', continent: 'america' },
  { country: 'Гамбия', continent: 'africa' },
  { country: 'Гана', continent: 'africa' },
  { country: 'Гватемала', continent: 'africa' },
  { country: 'Гвинея', continent: 'africa' },
  { country: 'Гвинея-Бисау', continent: 'africa' },
  { country: 'Германия', continent: 'europe' },
  { country: 'Гондурас', continent: 'america' },
  { country: 'Гренада', continent: 'islands' },
  { country: 'Греция', continent: 'europe' },
  { country: 'Грузия', continent: 'asia' },
  { country: 'Дания', continent: 'europe' },
  { country: 'Джибути', continent: 'africa' },
  { country: 'Доминика', continent: 'islands' },
  { country: 'Доминикана', continent: 'islands' },
  { country: 'Египет', continent: 'africa' },
  { country: 'Замбия', continent: 'africa' },
  { country: 'Зимбабве', continent: 'africa' },
  { country: 'Израиль', continent: 'europe' },
  { country: 'Индия', continent: 'asia' },
  { country: 'Индонезия', continent: 'asia' },
  { country: 'Иордания', continent: 'asia' },
  { country: 'Ирак', continent: 'asia' },
  { country: 'Иран', continent: 'asia' },
  { country: 'Ирландия', continent: 'europe' },
  { country: 'Исландия', continent: 'europe' },
  { country: 'Испания', continent: 'europe' },
  { country: 'Италия', continent: 'europe' },
  { country: 'Кабо-Верде', continent: 'africa' },
  { country: 'Казахстан', continent: 'asia' },
  { country: 'Камбоджа', continent: 'asia' },
  { country: 'Камерун', continent: 'africa' },
  { country: 'Канада', continent: 'america' },
  { country: 'Катар', continent: 'asia' },
  { country: 'Кения', continent: 'africa' },
  { country: 'Кипр', continent: 'europe' },
  { country: 'Киргизия', continent: 'asia' },
  { country: 'Кирибати', continent: 'islands' },
  { country: 'Китай', continent: 'asia' },
  { country: 'Колумбия', continent: 'america' },
  { country: 'Лаос', continent: 'asia' },
  { country: 'Латвия', continent: 'europe' },
  { country: 'Лесото', continent: 'africa' },
  { country: 'Либерия', continent: 'africa' },
  { country: 'Ливан', continent: 'asia' },
  { country: 'Ливия', continent: 'africa' },
  { country: 'Литва', continent: 'europe' },
  { country: 'Лихтенштейн', continent: 'europe' },
  { country: 'Люксембург', continent: 'europe' },
  { country: 'Маврикий', continent: 'africa' },
  { country: 'Мавритания', continent: 'africa' },
  { country: 'Мадагаскар', continent: 'africa' },
  { country: 'Малави', continent: 'africa' },
  { country: 'Малайзия', continent: 'asia' },
  { country: 'Мали', continent: 'africa' },
  { country: 'Мальдивы', continent: 'asia' },
  { country: 'Мальта', continent: 'europe' },
  { country: 'Марокко', continent: 'africa' },
  { country: 'Намибия', continent: 'africa' },
  { country: 'Науру', continent: 'islands' },
  { country: 'Непал', continent: 'asia' },
  { country: 'Нигер', continent: 'africa' },
  { country: 'Нигерия', continent: 'africa' },
  { country: 'Нидерланды', continent: 'europe' },
  { country: 'Никарагуа', continent: 'america' },
  { country: 'Новая Зеландия', continent: 'islands' },
  { country: 'Норвегия', continent: 'europe' },
  { country: 'ОАЭ', continent: 'asia' },
  { country: 'Оман', continent: 'asia' },
  { country: 'Пакистан', continent: 'asia' },
  { country: 'Палау', continent: 'islands' },
  { country: 'Панама', continent: 'america' },
  { country: 'Папуа - Новая Гвинея', continent: 'islands' },
  { country: 'Парагвай', continent: 'america' },
  { country: 'Перу', continent: 'america' },
  { country: 'Польша', continent: 'europe' },
  { country: 'Португалия', continent: 'europe' },
  { country: 'Руанда', continent: 'africa' },
  { country: 'Румыния', continent: 'europe' },
  { country: 'Россия', continent: 'europa' },
  { country: 'Сальвадор', continent: 'africa' },
  { country: 'Самоа', continent: 'islands' },
  { country: 'Сан-Марино', continent: 'europe' },
  { country: 'Саудовская Аравия', continent: 'asia' },
  { country: 'Сейшелы', continent: 'africa' },
  { country: 'Сенегал', continent: 'africa' },
  { country: 'Сербия', continent: 'europe' },
  { country: 'Сингапур', continent: 'asia' },
  { country: 'Сирия', continent: 'asia' },
  { country: 'Словакия', continent: 'europe' },
  { country: 'Словения', continent: 'europe' },
  { country: 'США', continent: 'america' },
  { country: 'Таджикистан', continent: 'asia' },
  { country: 'Таиланд', continent: 'asia' },
  { country: 'Танзания', continent: 'africa' },
  { country: 'Того', continent: 'africa' },
  { country: 'Тонга', continent: 'islands' },
  { country: 'Тринидад и Тобаго', continent: 'america' },
  { country: 'Тувалу', continent: 'islands' },
  { country: 'Тунис', continent: 'africa' },
  { country: 'Туркмения', continent: 'asia' },
  { country: 'Турция', continent: 'asia' },
  { country: 'Уганда', continent: 'africa' },
  { country: 'Узбекистан', continent: 'asia' },
  { country: 'Украина', continent: 'europe' },
  { country: 'Уругвай', continent: 'america' },
  { country: 'Фиджи', continent: 'islands' },
  { country: 'Филиппины', continent: 'asia' },
  { country: 'Финляндия', continent: 'europe' },
  { country: 'Франция', continent: 'europe' },
  { country: 'Хорватия', continent: 'europe' },
  { country: 'Чад', continent: 'africa' },
  { country: 'Черногория', continent: 'europe' },
  { country: 'Чехия', continent: 'europe' },
  { country: 'Чили', continent: 'africa' },
  { country: 'Швейцария', continent: 'europe' },
  { country: 'Швеция', continent: 'europe' },
  { country: 'Шри-Ланка', continent: 'asia' },
  { country: 'Эквадор', continent: 'africa' },
  { country: 'Эритрея', continent: 'africa' },
  { country: 'Эсватини', continent: 'africa' },
  { country: 'Эстония', continent: 'europe' },
  { country: 'Эфиопия', continent: 'africa' },
  { country: 'ЮАР', continent: 'africa' },
  { country: 'Южный Судан', continent: 'africa' }
];
let arr = [];
countries.forEach(item => {

});

console.log("а" === "А");